### ISSUE TITLE
Rename `GrayscaleImage` and `RGBAImage`

### ISSUE THREAD

**Issue by sanks64** [phenopolis/pluto#41]
Suggestions:

- `GrayscaleImage` -> `Image::GA` (GrayscaleAlpha)
- `RGBAImage` -> `Image::RGBA` (RedGreenBlueAlpha)

[libspng uses this naming as well](https://github.com/phenopolis/pluto/blob/9bce6e43539fbcfe80190a5526866812f2311ccc/src/pluto/bindings/lib_spng.cr#L45).

**Comment by sanks64** [comment]
@Vici37 What do you think?

**Comment by Vici37** [comment]
@sanks64 I would have a slight preference for the latter suggestion (`ImageGA` and `ImageRGBA`) so that the context that these class names composed entirely of capital letters is still there :) 

That being said, I [introduced the Grayscale image](https://github.com/phenopolis/pluto/pull/16#issue-1577174836) with the intention of providing a lot more methods for data extraction, which we then decided would [fit better in its own shard](https://github.com/phenopolis/pluto/pull/24#issuecomment-1446348766). As far as I know I was the only consumer of the Grayscale image - would it make sense that it should be removed from pluto then? I don't have strong opinions one way or the other on this matter, just bringing it up as on option.

**Comment by sanks64** [comment]
I'm actually using `GrayscaleImage` now, so I'd keep it

**Comment by Vici37** [comment]
Oh, cool! Carry on then :+1:
